# Generated by Django 4.2.30 on 2026-06-05 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('days_before_due', models.IntegerField(default=7, help_text='Number of days before the invoice due date to send a reminder.')),
                ('overdue_interval_days', models.IntegerField(default=3, help_text='Send a reminder every N days after the due date if still unpaid.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('verification', 'Email Verification Required'), ('verified', 'Email Verified Successfully'), ('password_reset', 'Password Reset Link'), ('password_changed', 'Password Changed Alert'), ('login_detected', 'New Login Alert'), ('account_locked', 'Account Security Lockout Alert'), ('org_invite', 'Organization Workspace Invitation'), ('org_added', 'Added to Workspace Alert'), ('role_changed', 'Workspace Role Changed Alert'), ('org_removed', 'Removed from Workspace Alert'), ('customer_created', 'Customer Onboarding Alert'), ('customer_updated', 'Customer Profile Updated Notice'), ('customer_portal_created', 'Customer Portal Created Alert'), ('customer_portal_invited', 'Customer Portal Invitation'), ('customer_portal_activated', 'Customer Portal Account Activated'), ('invoice_draft', 'Invoice Draft Created Alert'), ('invoice_finalized', 'Invoice Finalized Alert'), ('invoice_sent', 'Invoice Copy Sent to Client'), ('invoice_viewed', 'Invoice Viewed by Client Alert'), ('invoice_updated', 'Invoice Details Updated Alert'), ('invoice_cancelled', 'Invoice Cancelled Alert'), ('invoice_paid', 'Invoice Fully Paid Alert'), ('invoice_partially_paid', 'Invoice Partially Paid Alert'), ('invoice_overdue', 'Invoice Overdue Notice'), ('invoice_reopened', 'Invoice Reopened Alert'), ('payment_received', 'Payment Receipt Confirmation'), ('payment_failed', 'Payment Transaction Failed Alert'), ('refund_processed', 'Refund Processed Confirmation'), ('credit_note_issued', 'Credit Note Issued Notification'), ('org_created', 'Organization Created Alert'), ('org_settings_changed', 'Organization Settings Changed Alert'), ('org_billing_updated', 'Billing Settings Updated Notice'), ('sub_active', 'Subscription Activated Confirmation'), ('sub_renewed', 'Subscription Renewed Alert'), ('sub_expiring', 'Subscription Expiring Notice'), ('sub_cancelled', 'Subscription Cancelled Alert'), ('product_created', 'New Product Catalog Created'), ('product_price_updated', 'Catalog Pricing Updated Notice'), ('product_low_stock', 'Product Catalog Low Inventory Warning'), ('product_out_of_stock', 'Product Catalog Out of Stock Warning'), ('daily_summary', 'Daily Business Activity Summary'), ('weekly_summary', 'Weekly Business Activity Summary'), ('monthly_summary', 'Monthly Business Activity Summary')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'email_type')},
            },
        ),
    ]
