# Generated by Django 4.2.30 on 2026-06-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_reminderschedule_emaillog_emailsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='context_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
