# Generated by Django 4.2.30 on 2026-06-05 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gst_number',
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits and contain only numbers.', regex='^\\d{10}$')]),
        ),
    ]
