# Generated by Django 4.2.30 on 2026-06-05 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
