# Generated by Django 4.2.30 on 2026-06-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
